### ISSUE TITLE
LEGAL: Missing copyright notice

### ISSUE THREAD

**Issue by strager** [YangchenYe323/keyword-match-experiment#1]
keyword-match-experiment, at first glance, appears to be a derivative work of [quick-lint-js](https://quick-lint-js.com/) and also my [perfect-hash-tables repository](https://github.com/strager/perfect-hash-tables).

## quick-lint-js

Your project does not include a prominent notice as required by 5.a of the GPL3. From the license of quick-lint-js (GPL3):
>   5. Conveying Modified Source Versions.
> 
>   You may convey a work based on the Program, or the modifications to
> produce it from the Program, in the form of source code under the
> terms of section 4, provided that you also meet all of these conditions:
> 
>     a) The work must carry prominent notices stating that you modified
>     it, and giving a relevant date.

Writing "This project is a derivative work of quick-lint-js as of March 2023. quick-lint-js Copyright (C) 2020  Matthew "strager" Glazar." in the README is enough to fix this issue.

## perfect-hash-tables repository

My perfect-hash-tables repository is not open source and has no general license. I skimmed your commit c8637adc61eb4e4fefdcf6fe7a91cf0bac9822be and did not see any derivative work of my perfect-hash-tables repository which would not also fall under fair use. (I may have missed something, though.) However, there is a derivative of jQuery which I don't know the legality of.

If you want to copy code or algorithms from my perfect-hash-tables repository, I suggest asking me for permission first. You can email me at s@strager.net. I should make this clearer in my repository's README.

**Comment by YangchenYe323** [comment]
> Your project does not include a prominent notice as required by 5.a of the GPL3. From the license of quick-lint-js (GPL3):
> 
> >

Doing right away.



> My perfect-hash-tables repository is not open source and has no general license. I skimmed your commit [c8637ad](https://github.com/YangchenYe323/keyword-match-experiment/commit/c8637adc61eb4e4fefdcf6fe7a91cf0bac9822be) and did not see any derivative work of my perfect-hash-tables repository which would not also fall under fair use. (I may have missed something, though.) However, there is a derivative of jQuery which I don't know the legality of.

I took the `mixed.txt` and `non-keyword.txt` files form that repo.
